export default {
  ['zh-CN']: {
    '_settings': {
      rootWidth: '330px',
      numberInputMinWidth: '42px',
      controlWidth: '195px',
    },
    'editor.basicSettings': '基础设置',
    'editor.language': '语言',
    'editor.refThickness': '折射厚度',
    'editor.refFactor': '折射系数',
    'editor.refDispersion': '色散增益',
    'editor.refFresnelRange': '菲涅尔反射范围',
    'editor.refFresnelFactor': '菲涅尔反射强度',
    'editor.glareAngle': '高光角度',
    'editor.blurRadius': '模糊半径',
    'editor.blurMargin': '边缘模糊度',
    'editor.tint': '色调',
    'editor.shadowExpand': '阴影扩散',
    'editor.shadowFactor': '阴影强度',
    'editor.shadowPosition': '阴影位置',
    'editor.bgType': '背景类型',
    'editor.customBgImage': '自定义背景',
    'editor.shapeSettings': '形状设置',
    'editor.shapeWidth': '宽',
    'editor.shapeHeight': '高',
    'editor.shapeRadius': '圆角 (%)',
    'editor.shapeRoundness': '超椭圆系数',
    'editor.mergeRate': '形状融合度',
    'editor.showShape1': '显示第二个图形',
    'editor.animationSettings': '动画设置',
    'editor.springSizeFactor': '动画形变',
  },
  ['en-US']: {
    '_settings': {
      rootWidth: '380px',
      numberInputMinWidth: '42px',
      controlWidth: '195px',
    },
    'editor.basicSettings': 'Basic Settings',
    'editor.language': 'Language',
    'editor.refThickness': 'Thickness',
    'editor.refFactor': 'Refraction Factor',
    'editor.refDispersion': 'Dispersion Gain',
    'editor.refFresnelRange': 'Fresnel Size',
    'editor.refFresnelFactor': 'Fresnel Intensity',
    'editor.glareAngle': 'Glare Angle',
    'editor.blurRadius': 'Blur Radius',
    'editor.blurMargin': 'Blur Margin',
    'editor.tint': 'Tint',
    'editor.shadowExpand': 'Shadow Expand',
    'editor.shadowFactor': 'Shadow Intensity',
    'editor.shadowPosition': 'Shadow Position',
    'editor.bgType': 'Background',
    'editor.customBgImage': 'Custom Background',
    'editor.shapeSettings': 'Shape Settings',
    'editor.shapeWidth': 'Width',
    'editor.shapeHeight': 'Height',
    'editor.shapeRadius': 'Radius (%)',
    'editor.shapeRoundness': 'SuperEllipse Factor',
    'editor.mergeRate': 'Merge Rate',
    'editor.showShape1': 'Show 2nd Shape',
    'editor.animationSettings': 'Animation Settings',
    'editor.springSizeFactor': 'Animation Morph',
  },
}
